# NOTE: AudioKit/Specs was deleted from GitHub (404) and no pod here needs it.
# Using the CDN instead of cloning the multi-GB Specs git repo.
source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :osx, '14.2'
workspace 'eqMac.xcworkspace'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '14.2'
    end
  end
end

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  pod 'STPrivilegedTask', :git => 'https://github.com/sveinbjornt/STPrivilegedTask.git', :commit => 'fdca677c77adb166a2be4c5ea9c7580a738c49c9'
end

project 'app/eqMac.xcodeproj'

target 'eqMac' do
  project 'app/eqMac.xcodeproj'

  pod 'SwiftHTTP', '~> 3.0'
  # AMCoreAudio is gone: the bitgapp fork was deleted (404) and upstream was
  # renamed to SimplyCoreAudio, which broke the 3.4 podspec's source_files so
  # the pod installs with zero Swift sources. Replaced by our own CoreAudio
  # wrapper in Source/Audio/CoreAudio/ with a matching API surface.
  pod 'WebViewJavascriptBridge', '~> 6.0'
#  pod 'ReachabilitySwift'
  pod 'ReSwift', '~> 6.1'
  pod 'SwiftLint'
  pod 'Sparkle', '~> 2.9'
  # 7.1.3 fails to compile on modern libc++: SentryCrashMonitor_CPPException.cpp
  # used std::set_terminate without including <exception>. Fixed in 8.x/9.x.
  pod 'Sentry', '~> 9.9'
  pod 'EmitterKit', '~> 5.2.2'
  pod 'SwiftyJSON', '~> 4.2'
  pod 'SwiftyUserDefaults', '4.0'
  pod 'KeychainSwift', '~> 13.0'
  shared_pods

end


